"""Crear modelo docfir

Revision ID: 60952ef5bba7
Revises: 62215c760c16
Create Date: 2026-07-11 11:18:49.381005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60952ef5bba7'
down_revision: Union[str, Sequence[str], None] = '62215c760c16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docfir',
    sa.Column('docid', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nodid', sa.String(length=64), nullable=False),
    sa.Column('docnom', sa.String(length=255), nullable=False),
    sa.Column('mimtip', sa.String(length=100), nullable=False),
    sa.Column('tamano', sa.BigInteger(), nullable=False),
    sa.Column('verini', sa.String(length=20), nullable=False),
    sa.Column('verfin', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('hasori', sa.String(length=64), nullable=False),
    sa.Column('hasfir', sa.String(length=64), nullable=True),
    sa.Column('usrcre', sa.String(length=60), nullable=False),
    sa.Column('feccre', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usrmod', sa.String(length=60), nullable=True),
    sa.Column('fecmod', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.CheckConstraint("docnom != ''", name='ck_docfir_docnom_empty'),
    sa.CheckConstraint("estado IN ('BORRADOR', 'PENDIENTE', 'CANCELADO', 'ERROR')", name='ck_docfir_estado'),
    sa.CheckConstraint("hasfir IS NULL OR hasfir ~ '^[0-9a-fA-F]{64}$'", name='ck_docfir_hasfir_hex'),
    sa.CheckConstraint("hasori ~ '^[0-9a-fA-F]{64}$'", name='ck_docfir_hasori_hex'),
    sa.CheckConstraint("mimtip = 'application/pdf'", name='ck_docfir_mimtip_pdf'),
    sa.CheckConstraint("nodid != ''", name='ck_docfir_nodid_empty'),
    sa.CheckConstraint("usrcre != ''", name='ck_docfir_usrcre_empty'),
    sa.CheckConstraint("verini != ''", name='ck_docfir_verini_empty'),
    sa.CheckConstraint('tamano > 0', name='ck_docfir_tamano_positive'),
    sa.PrimaryKeyConstraint('docid')
    )
    op.create_index('ix_docfir_nodid_verini_unique', 'docfir', ['nodid', 'verini'], unique=True, postgresql_where=sa.text("activo = true AND estado != 'CANCELADO'"))
    op.create_foreign_key('fk_audifir_docid_docfir', 'audifir', 'docfir', ['docid'], ['docid'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_audifir_docid_docfir', 'audifir', type_='foreignkey')
    op.drop_index('ix_docfir_nodid_verini_unique', table_name='docfir', postgresql_where=sa.text("activo = true AND estado != 'CANCELADO'"))
    op.drop_table('docfir')
    # ### end Alembic commands ###
