"""Initial audifir model

Revision ID: 62215c760c16
Revises: 
Create Date: 2026-07-11 10:21:56.435760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62215c760c16'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audifir',
    sa.Column('audid', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('docid', sa.BigInteger(), nullable=True),
    sa.Column('evento', sa.String(length=40), nullable=False),
    sa.Column('usrid', sa.String(length=60), nullable=True),
    sa.Column('iporig', sa.String(length=45), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('fecope', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('audid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audifir')
    # ### end Alembic commands ###
