"""implement_docpaso

Revision ID: 82dc189cf4b8
Revises: f58b81150be2
Create Date: 2026-07-14 23:15:42.881433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82dc189cf4b8'
down_revision: Union[str, Sequence[str], None] = 'f58b81150be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docpaso',
    sa.Column('dpasid', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('docid', sa.BigInteger(), nullable=False),
    sa.Column('pasid', sa.BigInteger(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecdis', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecini', sa.DateTime(timezone=True), nullable=True),
    sa.Column('feclim', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecfin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('motivo', sa.String(length=500), nullable=True),
    sa.Column('pastip', sa.String(length=20), nullable=False),
    sa.Column('rolreq', sa.String(length=40), nullable=False),
    sa.Column('obliga', sa.Boolean(), nullable=False),
    sa.Column('plazo', sa.Integer(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verlock', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('usrcre', sa.String(length=60), nullable=False),
    sa.Column('feccre', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usrmod', sa.String(length=60), nullable=True),
    sa.Column('fecmod', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(estado IN ('COMPLETADO', 'RECHAZADO', 'OMITIDO', 'CANCELADO') AND fecfin IS NOT NULL) OR (estado NOT IN ('COMPLETADO', 'RECHAZADO', 'OMITIDO', 'CANCELADO'))", name='ck_docpaso_fecfin_req'),
    sa.CheckConstraint("(estado IN ('EN_PROCESO', 'COMPLETADO', 'RECHAZADO', 'OMITIDO', 'CANCELADO', 'VENCIDO') AND fecini IS NOT NULL) OR (estado NOT IN ('EN_PROCESO', 'COMPLETADO', 'RECHAZADO', 'OMITIDO', 'CANCELADO', 'VENCIDO'))", name='ck_docpaso_fecini_req'),
    sa.CheckConstraint("(estado IN ('RECHAZADO', 'OMITIDO', 'CANCELADO') AND motivo IS NOT NULL AND TRIM(motivo) != '') OR (estado NOT IN ('RECHAZADO', 'OMITIDO', 'CANCELADO'))", name='ck_docpaso_motivo_req'),
    sa.CheckConstraint("estado IN ('PENDIENTE', 'DISPONIBLE', 'EN_PROCESO', 'COMPLETADO', 'RECHAZADO', 'OMITIDO', 'CANCELADO', 'VENCIDO')", name='ck_docpaso_estado'),
    sa.CheckConstraint("motivo IS NULL OR TRIM(motivo) != ''", name='ck_docpaso_motivo_no_empty'),
    sa.CheckConstraint("pastip IN ('DILIGENCIAR', 'REVISAR', 'APROBAR', 'FIRMAR', 'ATESTIGUAR', 'CERRAR', 'PUBLICAR')", name='ck_docpaso_pastip'),
    sa.CheckConstraint("rolreq != ''", name='ck_docpaso_rolreq_empty'),
    sa.CheckConstraint("usrcre != ''", name='ck_docpaso_usrcre_empty'),
    sa.CheckConstraint('fecfin IS NULL OR fecini IS NULL OR fecfin >= fecini', name='ck_docpaso_fecfin_ge_fecini'),
    sa.CheckConstraint('feclim IS NULL OR fecdis IS NULL OR feclim >= fecdis', name='ck_docpaso_feclim_ge_fecdis'),
    sa.CheckConstraint('orden > 0', name='ck_docpaso_orden_positive'),
    sa.CheckConstraint('plazo IS NULL OR plazo > 0', name='ck_docpaso_plazo_positive'),
    sa.CheckConstraint('verlock > 0', name='ck_docpaso_verlock_positive'),
    sa.ForeignKeyConstraint(['docid'], ['docfir.docid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pasid'], ['flupaso.pasid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('dpasid')
    )
    op.create_index('uq_docpaso_docid_orden', 'docpaso', ['docid', 'orden'], unique=True)
    op.create_index('uq_docpaso_docid_pasid', 'docpaso', ['docid', 'pasid'], unique=True)
    
    op.create_index('idx_docpaso_docid_estado', 'docpaso', ['docid', 'estado'], postgresql_where=sa.text("estado IN ('DISPONIBLE', 'EN_PROCESO')"))
    op.create_index('idx_docpaso_feclim', 'docpaso', ['feclim'], postgresql_where=sa.text("estado IN ('DISPONIBLE', 'EN_PROCESO')"))
    op.create_index('idx_docpaso_estado_disp', 'docpaso', ['estado'], postgresql_where=sa.text("estado = 'DISPONIBLE'"))
    op.create_index('idx_docpaso_estado_venc', 'docpaso', ['estado'], postgresql_where=sa.text("estado = 'VENCIDO'"))
    
    op.execute("ALTER TABLE audifir DROP CONSTRAINT IF EXISTS ck_audifir_enttip")
    op.create_check_constraint(
        'ck_audifir_enttip',
        'audifir',
        "enttip IN ('DOCUMENTO', 'PLANTILLA', 'CAMPO', 'SISTEMA', 'FLUJODOC', 'FLUPASO', 'PASO')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_docpaso_docid_pasid', table_name='docpaso')
    op.drop_index('uq_docpaso_docid_orden', table_name='docpaso')
    op.drop_table('docpaso')
    
    op.execute("ALTER TABLE audifir DROP CONSTRAINT IF EXISTS ck_audifir_enttip")
    op.create_check_constraint(
        'ck_audifir_enttip',
        'audifir',
        "enttip IN ('DOCUMENTO', 'PLANTILLA', 'CAMPO', 'SISTEMA', 'FLUJODOC', 'FLUPASO')"
    )
    # ### end Alembic commands ###
