"""implementar_flujodoc_y_flupaso_docfir_update

Revision ID: f58b81150be2
Revises: f761788400b6
Create Date: 2026-07-14 21:21:21.133677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f58b81150be2'
down_revision: Union[str, Sequence[str], None] = 'f761788400b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flujodoc',
    sa.Column('fluid', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('flucod', sa.String(length=30), nullable=False),
    sa.Column('flunom', sa.String(length=150), nullable=False),
    sa.Column('fluver', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('usrcre', sa.String(length=60), nullable=False),
    sa.Column('feccre', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usrmod', sa.String(length=60), nullable=True),
    sa.Column('fecmod', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("estado IN ('BORRADOR', 'ACTIVO', 'INACTIVO')", name='ck_flujodoc_estado'),
    sa.CheckConstraint("flucod != ''", name='ck_flujodoc_flucod_empty'),
    sa.CheckConstraint("flunom != ''", name='ck_flujodoc_flunom_empty'),
    sa.CheckConstraint("usrcre != ''", name='ck_flujodoc_usrcre_empty'),
    sa.CheckConstraint('fluver > 0', name='ck_flujodoc_fluver_positive'),
    sa.PrimaryKeyConstraint('fluid')
    )
    op.create_index(op.f('ix_flujodoc_flucod'), 'flujodoc', ['flucod'], unique=False)
    op.create_index('uq_flujodoc_flucod_activo', 'flujodoc', ['flucod'], unique=True, postgresql_where=sa.text("estado = 'ACTIVO'"))
    op.create_index('uq_flujodoc_flucod_fluver', 'flujodoc', ['flucod', 'fluver'], unique=True)
    op.create_table('flupaso',
    sa.Column('pasid', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fluid', sa.BigInteger(), nullable=False),
    sa.Column('pascod', sa.String(length=30), nullable=False),
    sa.Column('pasnom', sa.String(length=100), nullable=False),
    sa.Column('pastip', sa.String(length=20), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('rolreq', sa.String(length=40), nullable=False),
    sa.Column('obliga', sa.Boolean(), nullable=False),
    sa.Column('plazo', sa.Integer(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('usrcre', sa.String(length=60), nullable=False),
    sa.Column('feccre', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usrmod', sa.String(length=60), nullable=True),
    sa.Column('fecmod', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("pascod != ''", name='ck_flupaso_pascod_empty'),
    sa.CheckConstraint("pasnom != ''", name='ck_flupaso_pasnom_empty'),
    sa.CheckConstraint("pastip IN ('DILIGENCIAR', 'REVISAR', 'APROBAR', 'FIRMAR', 'ATESTIGUAR', 'CERRAR', 'PUBLICAR')", name='ck_flupaso_pastip'),
    sa.CheckConstraint("rolreq != ''", name='ck_flupaso_rolreq_empty'),
    sa.CheckConstraint('orden > 0', name='ck_flupaso_orden_positive'),
    sa.CheckConstraint('plazo IS NULL OR plazo > 0', name='ck_flupaso_plazo_positive'),
    sa.ForeignKeyConstraint(['fluid'], ['flujodoc.fluid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('pasid')
    )
    op.create_index('idx_flupaso_fluid_activo', 'flupaso', ['fluid', 'activo'], unique=False)
    op.create_index('uq_flupaso_fluid_orden', 'flupaso', ['fluid', 'orden'], unique=True)
    op.create_index('uq_flupaso_fluid_pascod', 'flupaso', ['fluid', 'pascod'], unique=True)
    op.add_column('docfir', sa.Column('tplid', sa.BigInteger(), nullable=True))
    op.add_column('docfir', sa.Column('fluid', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_docfir_fluid'), 'docfir', ['fluid'], unique=False)
    op.create_index(op.f('ix_docfir_tplid'), 'docfir', ['tplid'], unique=False)
    op.create_foreign_key('fk_docfir_flujodoc', 'docfir', 'flujodoc', ['fluid'], ['fluid'], ondelete='RESTRICT')
    op.create_foreign_key('fk_docfir_plantill', 'docfir', 'plantill', ['tplid'], ['tplid'], ondelete='RESTRICT')
    
    op.execute("UPDATE docfir SET estado = 'EN_CURSO' WHERE estado = 'PENDIENTE'")
    op.execute("UPDATE docfir SET estado = 'ERROR_PUBLICACION' WHERE estado = 'ERROR'")
    
    op.execute('ALTER TABLE docfir DROP CONSTRAINT IF EXISTS ck_docfir_estado')
    op.create_check_constraint(
        'ck_docfir_estado',
        'docfir',
        "estado IN ('BORRADOR', 'PREPARADO', 'EN_CURSO', 'PENDIENTE_FIRMA', 'FIRMADO_PARCIAL', 'PENDIENTE_PUBLICACION', 'COMPLETADO', 'RECHAZADO', 'CANCELADO', 'ERROR_PUBLICACION')"
    )
    
    op.execute('ALTER TABLE audifir DROP CONSTRAINT IF EXISTS ck_audifir_enttip')
    op.create_check_constraint(
        'ck_audifir_enttip',
        'audifir',
        "enttip IN ('DOCUMENTO', 'PLANTILLA', 'CAMPO', 'SISTEMA', 'FLUJODOC', 'FLUPASO')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute('ALTER TABLE audifir DROP CONSTRAINT IF EXISTS ck_audifir_enttip')
    op.create_check_constraint(
        'ck_audifir_enttip',
        'audifir',
        "enttip IN ('DOCUMENTO', 'PLANTILLA', 'CAMPO', 'SISTEMA')"
    )
    
    op.execute("UPDATE docfir SET estado = 'PENDIENTE' WHERE estado IN ('PREPARADO', 'EN_CURSO', 'PENDIENTE_FIRMA', 'FIRMADO_PARCIAL', 'COMPLETADO')")
    op.execute("UPDATE docfir SET estado = 'ERROR' WHERE estado IN ('PENDIENTE_PUBLICACION', 'ERROR_PUBLICACION')")
    op.execute("UPDATE docfir SET estado = 'CANCELADO' WHERE estado = 'RECHAZADO'")
    
    op.execute('ALTER TABLE docfir DROP CONSTRAINT IF EXISTS ck_docfir_estado')
    op.create_check_constraint(
        'ck_docfir_estado',
        'docfir',
        "estado IN ('BORRADOR', 'PENDIENTE', 'CANCELADO', 'ERROR')"
    )
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_docfir_plantill', 'docfir', type_='foreignkey')
    op.drop_constraint('fk_docfir_flujodoc', 'docfir', type_='foreignkey')
    op.drop_index(op.f('ix_docfir_tplid'), table_name='docfir')
    op.drop_index(op.f('ix_docfir_fluid'), table_name='docfir')
    op.drop_column('docfir', 'fluid')
    op.drop_column('docfir', 'tplid')
    op.drop_index('uq_flupaso_fluid_pascod', table_name='flupaso')
    op.drop_index('uq_flupaso_fluid_orden', table_name='flupaso')
    op.drop_index('idx_flupaso_fluid_activo', table_name='flupaso')
    op.drop_table('flupaso')
    op.drop_index('uq_flujodoc_flucod_fluver', table_name='flujodoc')
    op.drop_index('uq_flujodoc_flucod_activo', table_name='flujodoc', postgresql_where=sa.text("estado = 'ACTIVO'"))
    op.drop_index(op.f('ix_flujodoc_flucod'), table_name='flujodoc')
    op.drop_table('flujodoc')
    # ### end Alembic commands ###
