"""implementar docpart

Revision ID: f61284a6c891
Revises: 82dc189cf4b8
Create Date: 2026-07-24 16:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f61284a6c891'
down_revision: Union[str, Sequence[str], None] = '82dc189cf4b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docpart',
    sa.Column('parid', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dpasid', sa.BigInteger(), nullable=False),
    sa.Column('usrid', sa.String(length=60), nullable=False),
    sa.Column('nomcom', sa.String(length=150), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('rolpro', sa.String(length=100), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('obliga', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('motivo', sa.String(length=500), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fecdis', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecini', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecfin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verlock', sa.Integer(), nullable=False),
    sa.Column('usrcre', sa.String(length=60), nullable=False),
    sa.Column('feccre', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usrmod', sa.String(length=60), nullable=True),
    sa.Column('fecmod', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(estado NOT IN ('RECHAZADO', 'OMITIDO', 'CANCELADO')) OR (motivo IS NOT NULL AND motivo != '')", name='ck_docpart_motivo_requerido'),
    sa.CheckConstraint("(fecini IS NULL) OR (fecfin IS NULL) OR (fecfin >= fecini)", name='ck_docpart_fechas_consistentes'),
    sa.CheckConstraint("estado IN ('PENDIENTE', 'DISPONIBLE', 'EN_PROCESO', 'COMPLETADO', 'RECHAZADO', 'OMITIDO', 'VENCIDO', 'CANCELADO')", name='ck_docpart_estado_valido'),
    sa.CheckConstraint('orden > 0', name='ck_docpart_orden_positivo'),
    sa.CheckConstraint('verlock >= 1', name='ck_docpart_verlock_positivo'),
    sa.ForeignKeyConstraint(['dpasid'], ['docpaso.dpasid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('parid'),
    sa.UniqueConstraint('dpasid', 'orden', name='uq_docpart_dpasid_orden'),
    sa.UniqueConstraint('dpasid', 'usrid', name='uq_docpart_dpasid_usrid')
    )
    
    op.create_index('idx_docpart_usrid_estado', 'docpart', ['usrid', 'estado'])
    op.create_index('idx_docpart_dpasid_activos', 'docpart', ['dpasid'], postgresql_where=sa.text("estado IN ('DISPONIBLE', 'EN_PROCESO')"))
    
    op.execute("ALTER TABLE audifir DROP CONSTRAINT IF EXISTS ck_audifir_enttip")
    op.create_check_constraint(
        'ck_audifir_enttip',
        'audifir',
        "enttip IN ('DOCUMENTO', 'PLANTILLA', 'CAMPO', 'SISTEMA', 'FLUJODOC', 'FLUPASO', 'PASO', 'PARTICIPANTE')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE audifir DROP CONSTRAINT IF EXISTS ck_audifir_enttip")
    op.create_check_constraint(
        'ck_audifir_enttip',
        'audifir',
        "enttip IN ('DOCUMENTO', 'PLANTILLA', 'CAMPO', 'SISTEMA', 'FLUJODOC', 'FLUPASO', 'PASO')"
    )
    
    op.drop_index('idx_docpart_dpasid_activos', table_name='docpart')
    op.drop_index('idx_docpart_usrid_estado', table_name='docpart')
    op.drop_table('docpart')
    # ### end Alembic commands ###
