"""Crear modelos de plantillas y campos

Revision ID: f761788400b6
Revises: 60952ef5bba7
Create Date: 2026-07-13 18:37:15.233313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f761788400b6'
down_revision: Union[str, Sequence[str], None] = '60952ef5bba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plantill',
    sa.Column('tplid', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tplcod', sa.String(length=30), nullable=False),
    sa.Column('tplnom', sa.String(length=150), nullable=False),
    sa.Column('tplver', sa.Integer(), nullable=False),
    sa.Column('nodid', sa.String(length=64), nullable=True),
    sa.Column('numpag', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('usrcre', sa.String(length=60), nullable=False),
    sa.Column('feccre', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usrmod', sa.String(length=60), nullable=True),
    sa.Column('fecmod', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("estado IN ('BORRADOR', 'ACTIVA', 'INACTIVA')", name='ck_plantill_estado'),
    sa.CheckConstraint("tplcod != ''", name='ck_plantill_tplcod_empty'),
    sa.CheckConstraint("tplnom != ''", name='ck_plantill_tplnom_empty'),
    sa.CheckConstraint("usrcre != ''", name='ck_plantill_usrcre_empty'),
    sa.CheckConstraint('numpag > 0', name='ck_plantill_numpag_positive'),
    sa.CheckConstraint('tplver > 0', name='ck_plantill_tplver_positive'),
    sa.PrimaryKeyConstraint('tplid')
    )
    op.create_index('ix_plantill_tplcod_activa_unique', 'plantill', ['tplcod'], unique=True, postgresql_where=sa.text("estado = 'ACTIVA'"))
    op.create_index('ix_plantill_tplcod_tplver_unique', 'plantill', ['tplcod', 'tplver'], unique=True)
    op.create_table('tplcamp',
    sa.Column('camid', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tplid', sa.BigInteger(), nullable=False),
    sa.Column('camcod', sa.String(length=30), nullable=False),
    sa.Column('camnom', sa.String(length=100), nullable=False),
    sa.Column('camtip', sa.String(length=20), nullable=False),
    sa.Column('pagina', sa.Integer(), nullable=False),
    sa.Column('posx', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('posy', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('ancho', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('alto', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('obliga', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('usrcre', sa.String(length=60), nullable=False),
    sa.Column('feccre', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usrmod', sa.String(length=60), nullable=True),
    sa.Column('fecmod', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("camcod != ''", name='ck_tplcamp_camcod_empty'),
    sa.CheckConstraint("camnom != ''", name='ck_tplcamp_camnom_empty'),
    sa.CheckConstraint("camtip IN ('TEXTO', 'TEXLAR', 'FECHA', 'CASILLA', 'OPCION', 'NOMBRE', 'TIPDOC', 'NUMDOC', 'FIRMA', 'SELLO')", name='ck_tplcamp_camtip'),
    sa.CheckConstraint('alto > 0 AND alto <= 1', name='ck_tplcamp_alto_range'),
    sa.CheckConstraint('ancho > 0 AND ancho <= 1', name='ck_tplcamp_ancho_range'),
    sa.CheckConstraint('orden > 0', name='ck_tplcamp_orden_positive'),
    sa.CheckConstraint('pagina > 0', name='ck_tplcamp_pagina_positive'),
    sa.CheckConstraint('posx + ancho <= 1', name='ck_tplcamp_posx_ancho_limit'),
    sa.CheckConstraint('posx >= 0 AND posx <= 1', name='ck_tplcamp_posx_range'),
    sa.CheckConstraint('posy + alto <= 1', name='ck_tplcamp_posy_alto_limit'),
    sa.CheckConstraint('posy >= 0 AND posy <= 1', name='ck_tplcamp_posy_range'),
    sa.ForeignKeyConstraint(['tplid'], ['plantill.tplid'], name='fk_tplcamp_tplid_plantill', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('camid')
    )
    op.create_index('ix_tplcamp_tplid_camcod_unique', 'tplcamp', ['tplid', 'camcod'], unique=True)
    op.create_index('ix_tplcamp_tplid_orden_unique', 'tplcamp', ['tplid', 'orden'], unique=True)
    op.add_column('audifir', sa.Column('enttip', sa.String(length=20), nullable=True))
    op.add_column('audifir', sa.Column('entid', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audifir', 'entid')
    op.drop_column('audifir', 'enttip')
    op.drop_index('ix_tplcamp_tplid_orden_unique', table_name='tplcamp')
    op.drop_index('ix_tplcamp_tplid_camcod_unique', table_name='tplcamp')
    op.drop_table('tplcamp')
    op.drop_index('ix_plantill_tplcod_tplver_unique', table_name='plantill')
    op.drop_index('ix_plantill_tplcod_activa_unique', table_name='plantill', postgresql_where=sa.text("estado = 'ACTIVA'"))
    op.drop_table('plantill')
    # ### end Alembic commands ###
